//------------------------------------------------------------------------------
// Automatically generated by the Fast Binary Encoding compiler, do not modify!
// https://github.com/chronoxor/FastBinaryEncoding
// Source: arena_common_ptr.fbe
// FBE version: 1.10.0.0
//------------------------------------------------------------------------------

#include "arena_common_ptr_ptr.h"

namespace arena_common_ptr {

} // namespace arena_common_ptr
