//------------------------------------------------------------------------------
// Automatically generated by the Fast Binary Encoding compiler, do not modify!
// https://github.com/chronoxor/FastBinaryEncoding
// Source: arena_ptr.fbe
// FBE version: 1.10.0.0
//------------------------------------------------------------------------------

#include "arena_test_ptr.h"

namespace arena_test {

} // namespace arena_test
