//------------------------------------------------------------------------------
// Automatically generated by the Fast Binary Encoding compiler, do not modify!
// https://github.com/chronoxor/FastBinaryEncoding
// Source: arena_ptr.fbe
// FBE version: 1.10.0.0
//------------------------------------------------------------------------------

#pragma once

#ifdef isset
#undef isset
#endif

#if defined(__clang__)
#pragma clang system_header
#elif defined(__GNUC__)
#pragma GCC system_header
#elif defined(_MSC_VER)
#pragma system_header
#endif

#include "fbe.h"
#include "memory/arena/arena.hpp"

#include "arena_common_ptr_ptr.h"

namespace arena_test {
using namespace FBE;
using allocator_type = std::pmr::polymorphic_allocator<char>;
using namespace ::arena_common_ptr;
} // namespace arena_test

namespace FBE {
using namespace ::arena_test;
} // namespace FBE

#include "fbe_ptr.h"

namespace arena_test {

} // namespace arena_test
