//------------------------------------------------------------------------------
// Automatically generated by the Fast Binary Encoding compiler, do not modify!
// https://github.com/chronoxor/FastBinaryEncoding
// Source: template_arena.fbe
// FBE version: 1.10.0.0
//------------------------------------------------------------------------------

#pragma once

#ifdef isset
#undef isset
#endif

#if defined(__clang__)
#pragma clang system_header
#elif defined(__GNUC__)
#pragma GCC system_header
#elif defined(_MSC_VER)
#pragma system_header
#endif

#include "fbe.h"
#include "memory/arena/arena.hpp"

#include "arena_common.h"

namespace template_arena {
using namespace FBE;
using allocator_type = std::pmr::polymorphic_allocator<char>;
using namespace ::arena_common;
} // namespace template_arena

namespace FBE {
using namespace ::template_arena;
} // namespace FBE

#include "fbe_ptr.h"

namespace template_arena {

} // namespace template_arena
