//------------------------------------------------------------------------------
// Automatically generated by the Fast Binary Encoding compiler, do not modify!
// https://github.com/chronoxor/FastBinaryEncoding
// Source: template_arena.fbe
// FBE version: 1.10.0.0
//------------------------------------------------------------------------------

#include "template_arena_ptr.h"

namespace template_arena {

} // namespace template_arena
